src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombre_pages;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_de_parution;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Auteur::class, inversedBy="livres")
     */
    private $auteurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="livres")
     */
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(?int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(?\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        $this->auteurs->removeElement($auteur);

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isbn', TextType::class, [
                'attr' => [
                    
                    'placeholder' => 'Entrez l\' ISBN'
                ]
            ])
            ->add('titre', TextType::class, [
                'attr' => [
                   
                    'placeholder' => 'Entrez le titre du bouquint'
                ]
            ])
            ->add('nombre_pages', null, [
                'attr' => [
                   
                    'placeholder' => 'Entrez le nombre de page'
                ]
            ])
            ->add('date_de_parution', DateType::class, [
                'widget' => 'single_text',
                
            ])
            ->add('note')
            ->add('auteurs', null,[
                'attr' => [
                    'multiple' => true
                ]
            ])
            ->add('genres', null,[
                'attr' => [
                    'multiple' => true
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/livre")
 */
class LivreController extends AbstractController
{
    /**
     * @Route("/", name="livre_index", methods={"GET"})
     */
    public function index(LivreRepository $livreRepository): Response
    {
        return $this->render('livre/index.html.twig', [
            'livres' => $livreRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="livre_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="livre_show", methods={"GET"})
     */
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="livre_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="livre_delete", methods={"POST"})
     */
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre{% endblock %}

{% block body %}
    <h1>Edit Livre</h1>

    {{ include('livre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('livre_index') }}">back to list</a>

    {{ include('livre/_delete_form.html.twig') }}
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres{% endblock %}


{% block body %}
 <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div id="logo">
        <h1><a href="/">BookStore</h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" title="" /></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>
          <li><a class="nav-link scrollto" href="/livre">Livres</a></li>
          <li><a class="nav-link scrollto" href="/auteur">Auteurs</a></li>
          <li class="dropdown"><a href="#"><span>Catégories</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="/login">Login</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

 <main id="main">
  <section class="container" data-aos="fade-up">
    <div ><div class="section-title text-center"> <p class="separator">Decouvrez les meilleurs ventes des livres disponibles</p>
    </div>
		<div class="container-table100">
		<div class="wrap-table100">
		    <div class="table100 ver2 m-b-110">
					<div class="table100-head">
				    <table>
    
                    <thead >
                    
                        <tr class="row100 head">
                            <th  class="row100 column1">Id</th>
                            <th  class="row100 column2">Isbn</th>
                            <th class="row100 column3">Titre</th>
                            <th class="row100 column4">Nombre_pages</th>
                            <th class="row100 column5">Date_de_parution</th>
                            <th class="row100 column6">Note</th>
                            <th class="row100 column7">actions</th>
                        </tr>
                     
                    </thead>
                </table>
            </div>

            <div class="table100-body js-pscroll">
             <table>
			    <tbody>
            {% for livre in livres %}
					<tr class="row100 body">
                        <td class="cell100 column1">{{ livre.id }}</td>
                        <td class="cell100 column2">{{ livre.isbn }}</td>
                        <td class="cell100 column3">{{ livre.titre }}</td>
                        <td class="cell100 column4">{{ livre.nombrePages }}</td>
                        <td class="cell100 column5">{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
                        <td class="cell100 column6">{{ livre.note }}</td>
                        <td class="cell100 column7">
                          <a href="{{ path('livre_show', {'id': livre.id}) }}">show</a>
                          <a href="{{ path('livre_edit', {'id': livre.id}) }}">edit</a>
                        </td>
                    </tr>
             {% else %}
            <tr class="row100 body">
                <td colspan="7">no records found</td>
            </tr>
            {% endfor %} 
        </tbody>
            </table>
         </div>
        </div>
       </div>
       </div>
       </div>

    <a href="{{ path('livre_new') }}">Create new</a>
    </div>
    </div>
    </section>
</main>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre{% endblock %}

{% block body %}
    <h1>Create new Livre</h1>

    {{ include('livre/_form.html.twig') }}

    <a href="{{ path('livre_index') }}">back to list</a>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block head %} 
  

{% endblock %}

{% block body %}
    <h1>Livre</h1>

    <table class="table">
        <tbody>
            <tr  class="row100 head">
                <th class="cell100 column1">Id</th>
                <td>{{ livre.id }}</td>
            </tr>
            <tr>
                <th class="cell100 column2">Isbn</th>
                <td>{{ livre.isbn }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ livre.titre }}</td>
            </tr>
            <tr>
                <th>Nombre_pages</th>
                <td>{{ livre.nombrePages }}</td>
            </tr>
            <tr>
                <th>Date_de_parution</th>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ livre.note }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('livre_index') }}">back to list</a>

    <a href="{{ path('livre_edit', {'id': livre.id}) }}">edit</a>

    {{ include('livre/_delete_form.html.twig') }}
{% endblock %}